language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: '8'
cache: yarn
before_script: npm install -g polymer-cli
after_success:
  - codeclimate-test-reporter < lcov.info
script:
  - xvfb-run npm run lint
  - xvfb-run polymer test --module-resolution=node --npm

