version: '3.3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
           - discovery.type=single-node
           - cluster.name=docker-cluster
           - bootstrap.memory_lock=true
           - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
           - http.cors.enabled=true
           - http.cors.allow-origin=/.*/
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ulimits:
          memlock:
            soft: -1
            hard: -1
        networks:
            - air-cruddy-network

volumes:
  esdata1:
    driver: local

networks:
    air-cruddy-network:
        driver: bridge